### ISSUE TITLE
Incorrect links

### ISSUE THREAD

**Issue by iembry-USGS** [cvitolo/r_CurveNumber#1]
Hi, thank you for creating this wonderful package. I had thought about creating a curve number function as part of my [`iemisc` package](https://gitlab.com/iembry/iemisc) before I searched online and found this one.

There are 2 link issues with the README:

[vignette](https://github.com/cvitolo/curvenumber/blob/master/vignettes/curvenumber-vignette.Rmd)

[report any issues or bugs](https://github.com/cvitolo/curvenumber/issues)

Above, I have used the correct links.

Thank you.

Irucka

**Comment by cvitolo** [comment]
This is now fixed, many thanks for spotting them!

**Comment by iembry-USGS** [comment]
@cvitolo  You're welcome and thank you for correcting the links.

Irucka
