### ISSUE TITLE
suggestion to calculate the weighted curve number

### ISSUE THREAD

**Issue by iembry-USGS** [cvitolo/r_CurveNumber#2]
Will you create a function to calculate the weighted curve number?

Please see page 21 of [Runoff Curve Number Computations](https://www.wcc.nrcs.usda.gov/ftpref/wntsc/H&H/training/runoff-curve-numbers1.pdf) for the formula.

The code below can be modified to accept a data.frame/data.table/tibble, list, matrix, etc.

```
# CN = vector of CNs
# area = vector of CNs

weighted_CN <- (CN * area) / sum(area)

```

Thank you.

Irucka

**Comment by cvitolo** [comment]
Hi Irucka, thanks for filing the issues.
Feel free to send a pull request

**Comment by iembry** [comment]
Hi @cvitolo  I just sent the pull request.

Thank you.

Irucka
