### ISSUE TITLE
README

### ISSUE THREAD

**Issue by iembry** [cvitolo/r_CurveNumber#5]
Hi @cvitolo 

1) The license is noted as License: GPL-3 in the README, but GPL-2 in the DESCRIPTION.

2) The contents of packs from the README does not match the package fields in the DESCRIPTION file:

**README**
packs <- c("dplyr", "zoo", "tgp", "stats", "utils", "BH", "Rcpp", "testthat",
           "qualV", "devtools")

**DESCRIPTION file:**

Depends: R (>= 3.0), rgdal, sp
Imports: raster, pracma, xts, zoo, Hmisc, hydromad, minpack.lm, graphics, stats, utils 
Suggests: devtools, knitr, rmarkdown, testthat, covr

Thank you.

Irucka

**Comment by cvitolo** [comment]
Thanks, I'll fix them later today!

**Comment by iembry** [comment]
@cvitolo  Thank you for letting me know.

Irucka

**Comment by iembry** [comment]
@cvitolo   After you merge the pull request, will you revise the README so that it matches the DESCRIPTION file?

I want to thank you in advance.

Irucka

**Comment by cvitolo** [comment]
Hello @iembry, I can no longer maintain this package. Would you like to become the package maintainer?

**Comment by iembry** [comment]
Hello @cvitolo, yes, I am willing to become the package maintainer.

Thank you for inquiring.

**Comment by cvitolo** [comment]
Great, glad you accepted. Many thanks!
I open a new issue to record the steps to make you a maintainer.

With regards to this issue, it will be resolved in the fork of the new maintainer [https://github.com/iembry/curvenumber](https://github.com/iembry/curvenumber)

**Comment by iembry** [comment]
Ok. That sounds good to me. Thank you for letting me know.

You are very welcome!
